---
title: "Homework 0: CRCD JupyterHub setup"
---

**Due 2025-09-05, 11:59pm**. *Instructions last updated 2025-09-01.*

This assignment is simply for you to get set up with the running Jupyter notebooks on the CRCD JupyterHub. We will use JupyterHub for in-class coding activities. Please follow the instructions exactly as listed. I'm interested in seeing if students can successfully load JupyterHub with the custom class conda environment; please don't submit screenshots using `pip` to install packages in the base environment.

## Instructions

1. Log in to the CRCD JupyterHub at [jupyter.crc.pitt.edu](https://jupyter.crc.pitt.edu) with your Pitt credentials. Type your username in lowercase and make sure that you are on the WIRELESS-PITTNET wifi network. If you are off-campus or not on WIRELESS-PITTNET, you will need to log in to the Pitt VPN through the GlobalProtect app. Instructions for setting that up are [here](https://services.pitt.edu/TDClient/33/Portal/KB/ArticleDet?ID=293). Reach out to Michael if you are not able to log in.
1. Select the following JupyterHub Session Configuration options:
	* Select Partition: **TEACH - 6 CPUs - 45GB**
	* Select Virtual Environment: Provide custom path
	* Custom Environment Path: **/ix/cs2731_2025f/class_env**. Note that this is different from what we did in class.
	* Account: you can leave this blank
	<br/>If you can't spawn a server at this point, try setting Account to `cs2731_2025f`. Also make sure you have enough space in your CRCD home directory. Check your usage by using `ssh` to log in to `h2p.crc.pitt.edu` and running `crc-quota`.
2. Click the following [nbgitpuller link](https://jupyter.crc.pitt.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fmichaelmilleryoder%2Fcs2731_jupyterhub&urlpath=lab%2Ftree%2Fcs2731_jupyterhub%2F&branch=main){target="_blank"}. This should load the latest version of `session2_preprocessing.ipynb`, which starts with a section header of **Import necessary packages** and should look like [this](https://github.com/michaelmilleryoder/cs2731_jupyterhub/blob/main/session2_preprocessing.ipynb){target="_blank"}. If it starts with **Install `nltk`** or anything else, close the notebook and right-click the notebook filename on the side panel to delete it. Click the nbgitpuller link again to load the latest version.
3. Double-click `session2_preprocessing.ipynb` on the left-hand side panel to open the Jupyter notebook.
4. Run the cells under the **Import necessary packages** section. That is all you have to do. You do not have to run the rest of the notebook.
5. Take a screenshot of the notebook (only the output of the first section is necessary) and submit it on Canvas. Ideally you are able to import `pandas` and `nltk`, but even if there are errors, that's okay! You will still get credit for the assignment, and I will message you on Canvas to try to figure any issues out.
